apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: prod-sc
  labels:
    app: zipkin
spec:
  ports:
    - port: 9411
      targetPort: 9411
      protocol: TCP
      name: http
  selector:
    app: zipkin

