apiVersion: v1
kind: Service
metadata:
  name: api-bp-server-sidecar-service
  namespace: prod-jae
spec:
  selector:
    app: api-bpserver-sidecar
  ports:
    - port: 80 # Porta exposta pelo servi√ßo
      targetPort: 3000 # Porta do container
  type: LoadBalancer # Pode ser LoadBalancer ou NodePort, dependendo do seu cluster

